settings:
  title: 'Status Page'
  url: 'https://status.hugo.md' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hugo-md # unique identifier
    name: Hugo's Blog
    url: 'https://hugo.md/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: sost-ovh
    name: Homelab
    url: 'https://sost.ovh'
    method: GET
    expectStatus: 404

  - id: soykaf-org
    name: Pleroma
    url: 'https://soykaf.org/api/v1/pleroma/healthcheck'
    method: GET
    expectStatus: 200
  
  - id: soykaf-org
    name: Mastodon
    url: 'https://melb.social/health'
    method: GET
    expectStatus: 200
