name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
usage_model = "bundled"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"
entry-point = "./"
